### ISSUE TITLE
Issue to trigger new releases

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJBalancing.jl#16]
@JuliaRegistrator register branch=master

Release notes:

- Update to support MLJBase 1.0 (#8)
- (**bug fix**) Drop support for Julia 1.6 as not actually supported at this time. Julia 1.7 and higher still supported (#8)
- (**feature addition**) Have `BalancedBaggingClassifier` report the actual number of bags used, `T_chosen` (commit [0ae67c7](https://github.com/JuliaAI/MLJBalancing.jl/commit/0ae67c7c524998caabaeae9850f7525778e9212b))

**Comment by EssamWisam** [comment]
@JuliaRegistrator register branch=master

**Release notes**:
- Added support for Julia 1.6
- Allow `model` to be specified as a positional argument in `BalancedModel` and `BalancedBaggingClassifier`
- Improving `BalancedModel` documentation

**Comment by EssamWisam** [comment]
@JuliaRegistrator register branch=master

**Release notes**:
- Added support for Julia 1.6
- Allow `model` to be specified as a positional argument in `BalancedModel` and `BalancedBaggingClassifier`
- Improving  documentation for `BalancedModel`

**Comment by EssamWisam** [comment]
@JuliaRegistrator register branch=master

Release Notes:
- Remove useless docstring

**Comment by EssamWisam** [comment]
@JuliaRegistrator register branch=master

Release Notes:

- **Bug fix:** flawed trait definitions were cleaned up. Thanks to @ablaom.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Overload new `constructor` trait for both models, so the models appear in the MLJ Model Registry and get integrated into the Model Browser (#27)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master
