### ISSUE TITLE
Support `model` (the classifier) as positional argument in `BalancedModel(...)`

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJBalancing.jl#17]
For consistency with `TunedModel`, `EnsembleModel`, `IteratedModel`, etc.

```julia
julia> BalancedModel(ConstantClassifier())
ERROR: MethodError: no method matching BalancedModel(::ConstantClassifier)
```

One could simply add `BalancedModel(model; kwargs...) = BalancedModel(; model, kwargs...)` but for a slightly more robust implementation, mimic https://github.com/JuliaAI/MLJIteration.jl/blob/b12c0bc284fd61136924767cfd2a219f98e9aab0/src/constructors.jl#L189

**Comment by EssamWisam** [comment]
Have just merged #18 after introducing this feature in a commit.
