### ISSUE TITLE
Problem with docstring for BalancedModel

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJBalancing.jl#19]
```julia
help?> BalancedModel
search: BalancedModel

  BalancedModel(; balancers=[], model=nothing)

  Wraps a classification model with balancers that resample the data before passing it to the model.

  Arguments
  ≡≡≡≡≡≡≡≡≡≡≡

    •  balancers::AbstractVector=[]: A vector of balancers (i.e., resampling models). Data
       passed to the model will be first passed to the balancers sequentially.

    •  model=nothing: The classification model which must be provided.
```

One does not provide a vector of balancers but provides the balancers with user-chosen names. Perhaps something along these lines (modelled on the `MLJ.Stack` docstring):

 ```julia
    BalancedModel(; model=nothing, name1=balancer1, name2=balancer2,...)
```

And on reflection, I think it would be good to give at least one example to clarify this further. I know we have this is in the readme, but that is much less discoverable, as most users will call this from MLJ.

**Comment by EssamWisam** [comment]
@ablaom Let me know if the docstring is acceptable now

**Comment by ablaom** [comment]
Looks good to me, thanks.
