### ISSUE TITLE
Support Julia 1.6

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJBalancing.jl#20]
See this discussion:

https://github.com/JuliaAI/Imbalance.jl/issues/65

**Comment by EssamWisam** [comment]
![image](https://github.com/JuliaAI/MLJBalancing.jl/assets/49572294/d5ceda72-3d8c-4a58-bc1b-3cb775791808)

**Comment by EssamWisam** [comment]
@ablaom `MLJBalancing 0.1.2` is out.
